<?php

/**
 * @file
 * StratosERP Xero sync module.
 *
 * Synchronises various content with Xero.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 *
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 *   The entity type being updated.
 *
 * @return array
 *   The fields to add the to entity type.
 */
function se_xero_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];

  // Add the xero uuid field to all node types.
  if ($entity_type->id() === 'se_business') {
    // TODO Check for appropriate bundles?
    $fields['se_xero_uuid'] = BaseFieldDefinition::create('string')
      ->setLabel(t('StratosERP Xero uuid'))
      ->setName('StratosERP Xero uuid')
      ->setRevisionable(TRUE)
      ->setDescription(t('Used to keep things in sync with Xero.'))
      ->setTranslatable(TRUE)
      ->setSetting('default_value', '')
      ->setDisplayOptions('view', [
        'label' => 'hidden',
        'region' => 'hidden',
      ])
      ->setDisplayOptions('form', [
        'region' => 'hidden',
      ]);
  }

  return $fields;
}
