<?php

function se_bill_form_node_se_bill_form_alter(&$form) {
  Drupal::service('se_core.set_field')->setReferenceField($form, 'field_bu_ref', 'field_bu_ref');

  $config = \Drupal::configFactory()->get('se_bill.settings');
  if ($bill_status = $config->get('bill_status_term')) {
    \Drupal::service('se_core.set_field')
      ->setTaxonomyField($form, 'field_bi_status_ref', $bill_status);
  }
}
