<?php

declare(strict_types=1);

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function se_business_form_se_business_se_business_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');
}

/**
 * Implements hook_theme().
 */
function se_business_theme() {
  $theme = [];

  $theme['se_business'] = [
    'render element' => 'elements',
    'file' => 'se_business.page.inc',
    'template' => 'se_business',
  ];

  return $theme;
}
