<?php

namespace Drupal\se_item_line\Plugin\Field\FieldType;

use Drupal\dynamic_entity_reference\Plugin\Field\FieldType\DynamicEntityReferenceFieldItemList;

/**
 * Represents a configurable entity se_item_line field.
 */
class ItemLineFieldItemList extends DynamicEntityReferenceFieldItemList {

  /**
   * {@inheritdoc}
   */
  public function referencedEntities() {
    return parent::referencedEntities(); // TODO: Change the autogenerated stub
  }

}
