<?php

namespace Drupal\se_line_item\Plugin\Field\FieldType;

use Drupal\dynamic_entity_reference\Plugin\Field\FieldType\DynamicEntityReferenceFieldItemList;

/**
 * Represents a configurable entity se_line_item field.
 */
class LineItemFieldItemList extends DynamicEntityReferenceFieldItemList {

  /**
   * {@inheritdoc}
   */
  public function referencedEntities() {
    return parent::referencedEntities(); // TODO: Change the autogenerated stub
  }

}
