<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Datetime\DrupalDateTime;

function se_timekeeping_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'comment_se_timekeeping_form') {

    // If the business ref is not set, try and Retrieve the entity
    // the comment is being attached to.
    /** @var \Drupal\node\Entity\Node $node */
    if (empty($form['field_bu_ref']['widget'][0]['target_id']['#default_value'])
    && $node = $form_state->getFormObject()->getEntity()->getCommentedEntity()) {
      $form['field_bu_ref']['widget'][0]['target_id']['#default_value'] =
        \Drupal::service('se_customer.service')->lookupCustomer($node);
    }

    // If the subject is not set, set one.
    // TODO this truncate is icky.
    if (isset($node) && empty($form['subject']['widget'][0]['value']['#default_value'])) {
      // Set the default subject to the title of the node.
      $date = new DrupalDateTime();
      $form['subject']['widget'][0]['value']['#default_value'] =
        t('@title - @user - @now', [
          '@title' => mb_strimwidth($node->getTitle(), 0, 20) . '...',
          '@user' => mb_strimwidth(\Drupal::currentUser()->getAccountName(), 0, 20) . '...',
          '@now' => \Drupal::service('date.formatter')->format($date->getTimestamp(), 'short', '', NULL),
        ]);
    }

    // Now hide the fields.
    $form['field_bu_ref']['widget']['#access'] = FALSE;
    $form['subject']['widget']['#access'] = FALSE;
  }
}
