<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Datetime\DrupalDateTime;

function se_timekeeping_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'comment_se_timekeeping_form') {

    // If the business ref is not set, try and Retrieve the entity
    // the comment is being attached to.
    if (empty($form['field_bu_ref']['widget'][0]['target_id']['#default_value'])
    && $node = $form_state->getFormObject()->getEntity()->getCommentedEntity()) {
      $form['field_bu_ref']['widget'][0]['target_id']['#default_value'] =
        \Drupal::service('se_customer.service')->lookupCustomer($node);
    }

    // If the subject is not set, set one.
    if (empty($form['subject']['widget'][0]['value']['#default_value']) && $node) {
      // Set the default subject to the title of the node.
      $date = new DrupalDateTime();
      $form['subject']['widget'][0]['value']['#default_value'] =
        t('@title - @user - @now', [
          '@title' => $node->getTitle(),
          '@user' => \Drupal::currentUser()->getAccountName(),
          '@now' => \Drupal::service('date.formatter')->format($date->getTimestamp(), 'short', '', NULL),
        ]);
    }

    // Now hide the fields.
    $form['field_bu_ref']['widget']['#access'] = FALSE;
    $form['subject']['widget']['#access'] = FALSE;
  }
}
