<?php

/**
 * @file
 * Contains se_information.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function se_information_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the se_information module.
    case 'help.page.se_information':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function se_information_theme() {
  $theme = [];
  $theme['se_information'] = [
    'render element' => 'elements',
    'file' => 'se_information.page.inc',
    'template' => 'se_information',
  ];
  $theme['se_information_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'se_information.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function se_information_theme_suggestions_se_information(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#se_information'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'se_information__' . $sanitized_view_mode;
  $suggestions[] = 'se_information__' . $entity->bundle();
  $suggestions[] = 'se_information__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'se_information__' . $entity->id();
  $suggestions[] = 'se_information__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

function se_information_form_se_information_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('se_core.set_field')->setReferenceField($form, 'field_bu_ref', 'field_bu_ref');
}
