<?php

namespace Drupal\se_stock_item\Form;

use Drupal\Core\Entity\ContentEntityForm;
use Drupal\Core\Form\FormStateInterface;

/**
 * Form controller for Stock item edit forms.
 *
 * @ingroup se_stock_item
 */
class StockItemForm extends ContentEntityForm {

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
    /* @var $entity \Drupal\se_stock_item\Entity\StockItem */
    $form = parent::buildForm($form, $form_state);

    $entity = $this->entity;

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    $values = $form_state->getValues();

    if (empty($values['field_si_serial'][0]['value']) && empty($values['field_si_virtual'][0]['value'])) {
      $form_state->setErrorByName('field_si_serial',
        $this->t('Non virtual stock items require a serial number.'));
    }
    return parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state) {
    $entity = &$this->entity;

    $status = parent::save($form, $form_state);

    switch ($status) {
      case SAVED_NEW:
        drupal_set_message($this->t('Created the %label Stock item.', [
          '%label' => $entity->label(),
        ]));
        break;

      default:
        drupal_set_message($this->t('Saved the %label Stock item.', [
          '%label' => $entity->label(),
        ]));
    }
    $form_state->setRedirect('entity.se_stock_item.canonical', ['se_stock_item' => $entity->id()]);
  }

}
