<?php

/**
 * @file
 * Core functions for stratos erp module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Term;
use Drupal\se_core\ErpCore;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param RouteMatchInterface $route_match
 *
 * @return TranslatableMarkup
 */
function se_core_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'se_core_main') {
    return t('Main console page.');
  }
  return NULL;
}

/**
 * Change the node buttons to be what we want.
 *
 * Implements hook_form_alter().
 *
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function se_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Make a list of forms from the core types.
  $se_forms = array_map(function ($value) {
    return 'node_' . $value . '_form';
  }, ErpCore::NODE_TYPES);

  if (in_array($form_id, $se_forms, TRUE)) {
    // We don't need the publish button, anywhere.
    se_core_hide_publish_buttons($form);

    // Hide the title fields for some node types.
    if (!in_array($form_id, [
      'node_se_customer_form', 'node_se_contact_form', 'node_se_supplier_form', 'node_se_ticket_form'
    ])) {
      // Pre-fill the title field with sensible values.
      se_core_populate_title_field($form);
    }
  }
}

/**
 * Helper function to hide the publish buttons.
 *
 * @param array $form
 *   Form array to be manipulated.
 */
function se_core_hide_publish_buttons(array &$form) {
  // This should work.
  $form['actions']['unpublish']['#access'] = FALSE;
  $form['actions']['publish']['#access'] = FALSE;

  // But it doesn't. Sledge hammer time.
  unset($form['actions']['unpublish'], $form['actions']['publish']);

  // Ensure that we can 'Save' as well.
  $form['actions']['submit']['#access'] = TRUE;
}

/**
 * Nodes are handy, but we don't really need the title field.
 *
 * @param array $form
 *   Form array to be manipulated.
 */
function se_core_populate_title_field(array &$form) {
  //$form['title']['#hidden'] = TRUE;
  $form['title']['widget'][0]['value']['#default_value'] = t('@user - @date', [
    '@user' => get_current_user(),
    '@date' => date('j-m-Y'),
  ])->render();
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function se_core_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_se_core_user_login_form_submit';
}

/**
 * Custom submit handler for login form.
 *
 * @param $form
 * @param FormStateInterface $form_state
 *
 */
function _se_core_user_login_form_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirect('<front>');
}

function se_core_theme() {
  return [
    'se_core_admin_page' => [
      'variables' => [
        'counters' => [],
        'general_info' => [],
        'requirements' => NULL,
      ],
    ],
  ];
}

/**
 * Helper function for modules to install their own terms.
 * @param $taxonomy
 * @param $terms
 */
function se_core_create_terms($taxonomy, $terms) {
  foreach ($terms as $new_term) {
    $term = taxonomy_term_load_multiple_by_name($new_term, $taxonomy);
    if (empty($term)) {
      Term::create([
        'parent' => [],
        'name'   => $new_term,
        'vid'    => $taxonomy,
      ])->save();
    }
  }
}
