<?php

declare(strict_types=1);

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function se_invoice_form_node_se_invoice_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $service = \Drupal::service('stratoserp.set_field');
  $service->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');
  $service->setReferenceField($form, 'se_co_ref', 'se_co_ref');
}

/**
 * Implements hook_theme().
 */
function se_invoice_theme() {
  $theme = [];

  $theme['se_invoice'] = [
    'render element' => 'elements',
    'file' => 'se_invoice.page.inc',
    'template' => 'se_invoice',
  ];

  return $theme;
}
