<?php

declare(strict_types=1);

/**
 * @file
 */

use Drupal\se_invoice\Entity\Invoice;

/**
 * Implements hook_theme().
 */
function se_invoice_theme(): array {
  $theme = [];

  $theme['se_invoice'] = [
    'render element' => 'elements',
    'file' => 'se_invoice.page.inc',
    'template' => 'se_invoice',
  ];

  return $theme;
}

function se_invoice_se_invoice_presave(Invoice $invoice) {
  // New entities have nothing to store here.
  if ($invoice->isNew()) {
    return;
  }

  \Drupal::service('se_invoice.service')->storeBalance($invoice);
}

function se_invoice_se_invoice_insert(Invoice $invoice) {
  \Drupal::service('se_invoice.service')->statusTotalInsert($invoice);
}

function se_invoice_se_invoice_update(Invoice $invoice) {
  // This is set by payments or they would be re-saving save the invoice.
  if ($invoice->getSkipInvoiceSaveEvents()) {
    return;
  }
  
  \Drupal::service('se_invoice.service')->statusTotalUpdate($invoice);
}

function se_invoice_se_invoice_delete(Invoice $invoice) {
  // This is set by payments or they would be re-saving save the invoice.
  if ($invoice->getSkipInvoiceSaveEvents()) {
    return;
  }
  
  \Drupal::service('se_invoice.service')->deleteUpdate($invoice);
}
