<?php

/**
 * @file
 * Contains se_document.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function se_document_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the se_document module.
    case 'help.page.se_document':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function se_document_theme() {
  $theme = [];
  $theme['se_document'] = [
    'render element' => 'elements',
    'file' => 'se_document.page.inc',
    'template' => 'se_document',
  ];
  $theme['se_document_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'se_document.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function se_document_theme_suggestions_se_document(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#se_document'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'se_document__' . $sanitized_view_mode;
  $suggestions[] = 'se_document__' . $entity->bundle();
  $suggestions[] = 'se_document__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'se_document__' . $entity->id();
  $suggestions[] = 'se_document__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

function se_document_form_node_se_document_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('se_core.set_business')->setBusiness($form, $form_state);
}
