<?php

declare(strict_types=1);

/**
 * @file
 */

use Drupal\se_invoice\Entity\Invoice;

/**
 * Implements hook_theme().
 */
function se_timekeeping_theme() {
  $theme = [];

  $theme['se_timekeeping'] = [
    'render element' => 'elements',
    'file' => 'se_timekeeping.page.inc',
    'template' => 'se_timekeeping',
  ];

  return $theme;
}

function se_timekeeping_se_invoice_presave(Invoice $invoice) {
  \Drupal::service('se_invoice.service')->timekeepingMarkItemsUnBilled($invoice);
}

function se_payment_se_invoice_insert(Invoice $invoice) {
  \Drupal::service('se_invoice.service')->timekeepingMarkItemsBilled($invoice);
}

function se_payment_se_invoice_update(Invoice $invoice) {
  \Drupal::service('se_invoice.service')->timekeepingMarkItemsBilled($invoice);
}

function se_payment_se_invoice_delete(Invoice $invoice) {
  \Drupal::service('se_invoice.service')->timekeepingMarkItemsUnBilled($invoice);
}
