<?php

declare(strict_types=1);

/**
 * @file
 */

use Drupal\se_goods_receipt\Entity\GoodsReceipt;

/**
 * Implements hook_theme().
 */
function se_goods_receipt_theme() {
  $theme = [];

  $theme['se_goods_receipt'] = [
    'render element' => 'elements',
    'file' => 'se_goods_receipt.page.inc',
    'template' => 'se_goods_receipt',
  ];

  return $theme;
}

function se_goods_reeipt_se_goods_receipt_presave(GoodsReceipt $goodsReceipt) {
  \Drupal::service('se_goods_receipt.service')->createItems($goodsReceipt);
}

function se_goods_receipt_se_goods_receipt_insert(GoodsReceipt $goodsReceipt) {
  \Drupal::service('se_goods_receipt.service')->updateFields($goodsReceipt);
}
