<?php

declare(strict_types=1);

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function se_contact_form_node_se_contact_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');

  $config = \Drupal::configFactory()->get('se_contact.settings');
  if ($contact_type = (int) $config->get('main_contact_term')) {
    \Drupal::service('stratoserp.set_field')
      ->setTaxonomyField($form, 'se_co_type_ref', $contact_type);
  }
}

/**
 * Implements hook_theme().
 */
function se_contact_theme() {
  $theme = [];

  $theme['se_contact'] = [
    'render element' => 'elements',
    'file' => 'se_contact.page.inc',
    'template' => 'se_contact',
  ];

  return $theme;
}
