<?php

declare(strict_types=1);

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;

/**
 *
 */
function se_customer_form_se_customer_se_customer_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');
}

/**
 * Implements hook_theme().
 */
function se_customer_theme() {
  $theme = [];

  $theme['se_customer'] = [
    'render element' => 'elements',
    'file' => 'se_customer.page.inc',
    'template' => 'se_customer',
  ];

  return $theme;
}
