<?php

/**
 * @file
 * Custom functions for item manipulation.
 */

use Drupal\stratoserp\ErpCore;
use Drupal\Core\Form\FormStateInterface;

/**
 * Wherever the se_item_lines are used, replace the drupal autocomplete
 * with our own that does price field updates.
 *
 * TODO - put this in the widget.
 *
 * Implements hook_form_alter().
 */
function se_item_line_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Make a list of forms from the core types.
  $se_item_forms = array_map(function ($value) {
    return 'node_' . $value . '_form';
  }, array_keys(ErpCore::SE_ITEM_LINE_BUNDLES));

  if (in_array($form_id, $se_item_forms, TRUE)) {
    $form['#attached']['library'][] = 'core/drupal.ajax';
    $form['#attached']['library'][] = 'se_item_line/drupal.autocomplete';
  }
}

/**
 * Implements hook_theme().
 */
function se_item_line_theme(): array {
  return [
    'se_item_line_widget' => [
      'variables' => [
        'target_type' => '',
        'target_id' => '',
        'quantity' => '',
        'price' => '',
        'serial' => '',
        'completed_date' => '',
        'note' => '',
      ],
    ],

  ];
}
