<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function se_supplier_form_node_se_supplier_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');
}

/**
 * Implements hook_theme().
 */
function se_supplier_theme() {
  $theme = [];

  $theme['se_supplier'] = [
    'render element' => 'elements',
    'file' => 'se_supplier.page.inc',
    'template' => 'se_supplier',
  ];

  return $theme;
}
