<?php

declare(strict_types=1);

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function se_quote_theme() {
  $theme = [];

  $theme['se_quote'] = [
    'render element' => 'elements',
    'file' => 'se_quote.page.inc',
    'template' => 'se_quote',
  ];
  $theme['entity_print__se_quote'] = [
    'file' => 'se_quote.page.inc',
    'template' => 'entity-print--se-quote',
    'variables' => [
      'title' => '',
      'content' => NULL,
      'store_logo' => NULL,
      'entity_print_css' => NULL,
    ],
  ];

  return $theme;
}
