<?php

/**
 * @file
 */

use Drupal\Core\Form\FormStateInterface;

/**
 *
 */
function se_quote_form_node_se_quote_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');
  \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_co_ref', 'se_co_ref');

  $config = \Drupal::configFactory()->get('se_quote.settings');
  if ($quote_status = $config->get('quote_status_term')) {
    \Drupal::service('stratoserp.set_field')
      ->setTaxonomyField($form, 'se_status_ref', $quote_status);
  }
}
