<?php

use Drupal\Core\Form\FormStateInterface;

function se_invoice_form_node_se_invoice_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('se_core.set_field')->setReferenceField($form, 'field_bu_ref', 'field_bu_ref');
  \Drupal::service('se_core.set_field')->setReferenceField($form, 'field_co_ref', 'field_co_ref');

  $config = \Drupal::configFactory()->get('se_invoice.settings');
  if ($status_term = $config->get('invoice_status_term')) {
    \Drupal::service('se_core.set_field')
      ->setTaxonomyField($form, 'field_in_status_ref', $status_term);
  }

}