<?php

/**
 * @file
 * Contains se_stock_item.module.
 */

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function se_stock_item_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the se_stock_item module.
    case 'help.page.se_stock_item':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Stock item') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * Limit stock item reference fields using a custom autocomplete.
 */
function se_stock_item_field_widget_entity_reference_paragraphs_form_alter(&$element, FormStateInterface $form_state, $context) {
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof EntityFormInterface) {
    $entity = $form_object->getEntity();

    if ($entity->getEntityTypeId() == 'node') {
      $entity_type_bundle = $entity->bundle();

      // Exist if not a Stratos ERP form
      if (!in_array($entity_type_bundle, SE_CORE_NODE_TYPES)) {
        return;
      }

      if (isset($element['subform']['field_it_stock_item']['#type']) && $element['#paragraph_type'] == 'se_items') {
        $target = $element['subform']['field_it_stock_item']['widget'][0]['target_id'];

        // Use our custom selection handler.
        $target['#selection_handler'] = 'stock_item:selection';

        // Pass the bundle id to the handler.
        $target['#selection_settings']['event_type_bundle'] = $entity_type_bundle;
      }
    }
  }
}

