<?php

/**
 * @file
 * Contains se_stock_item.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function se_stock_item_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the se_stock_item module.
    case 'help.page.se_stock_item':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Stock item') . '</p>';
      return $output;

    default:
  }
}

function se_stock_item_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('se_stock_item.set_item')->setItem($form, $form_state);
}