<?php

declare(strict_types=1);

/**
 * @file
 * Contains se_item.module.
 */

use Drupal\stratoserp\Constants;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\se_invoice\Entity\Invoice;

/**
 * Implements hook_help().
 */
function se_item_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.se_item') {
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('') . '</p>';
    return $output;
  }
}

/**
 * Implements hook_theme().
 */
function se_item_theme() {
  $theme = [];
  $theme['se_item'] = [
    'render element' => 'elements',
    'file' => 'se_item.page.inc',
    'template' => 'se_item',
  ];
  $theme['se_item_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'se_item.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function se_item_theme_suggestions_se_item(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#se_item'];
  $sanitized_view_mode = str_replace('.', '_', $variables['elements']['#view_mode']);

  $suggestions[] = 'se_item__' . $sanitized_view_mode;
  $suggestions[] = 'se_item__' . $entity->bundle();
  $suggestions[] = 'se_item__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'se_item__' . $entity->id();
  $suggestions[] = 'se_item__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function se_item_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if (isset($fields['se_code']) && in_array($bundle, Constants::SE_ITEM_BUNDLES, TRUE)) {
    $fields['se_code']->addConstraint('UniqueItem', []);
  }
}

