<?php

namespace Drupal\se_accounting\Plugin\Field\FieldType;

use Drupal\Core\Field\Plugin\Field\FieldType\IntegerItem;

/**
 * Represents a configurable entity se_item_line field.
 */
class CurrencyFieldItemList extends IntegerItem {

  /**
   * {@inheritdoc}
   */
  public function referencedEntities() {
    return parent::referencedEntities(); // TODO: Change the autogenerated stub
  }

}
