<?php

declare(strict_types=1);

/**
 * @file
 */

/**
 * Implements hook_form_alter().
 */
function se_bill_form_node_se_bill_form_alter(&$form) {
  \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');

  $config = \Drupal::configFactory()->get('se_bill.settings');
  if ($bill_status = $config->get('bill_status_term')) {
    \Drupal::service('stratoserp.set_field')
      ->setTaxonomyField($form, 'se_status_ref', $bill_status);
  }
}

/**
 * Implements hook_theme().
 */
function se_bill_theme() {
  $theme = [];

  $theme['se_bill'] = [
    'render element' => 'elements',
    'file' => 'se_bill.page.inc',
    'template' => 'se_bill',
  ];

  return $theme;
}
