<?php

declare(strict_types=1);

/**
 * @file
 */

/**
 *
 */
function se_bill_form_node_se_bill_form_alter(&$form) {
  \Drupal::service('stratoserp.set_field')->setReferenceField($form, 'se_bu_ref', 'se_bu_ref');

  $config = \Drupal::configFactory()->get('se_bill.settings');
  if ($bill_status = $config->get('bill_status_term')) {
    \Drupal::service('stratoserp.set_field')
      ->setTaxonomyField($form, 'se_status_ref', $bill_status);
  }
}
