<?php

use Drupal\Core\Form\FormStateInterface;

function se_purchase_order_form_node_se_purchase_order_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('se_core.set_field')->setReferenceField($form, 'field_bu_ref', 'field_bu_ref');
  \Drupal::service('se_core.set_field')->setReferenceField($form, 'field_co_ref', 'field_co_ref');

  $config = \Drupal::configFactory()->get('se_purchase_order.settings');
  if ($purchase_order_status = $config->get('main_purchase_order_term')) {
    \Drupal::service('se_core.set_field')
      ->setTaxonomyField($form, 'field_po_status_ref', $purchase_order_status);
  }
}
