<?php

use Drupal\Core\Form\FormStateInterface;

function se_quote_form_node_se_quote_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('se_core.set_field')->setReferenceField($form, 'field_bu_ref', 'field_bu_ref');
  \Drupal::service('se_core.set_field')->setReferenceField($form, 'field_co_ref', 'field_co_ref');

  $config = \Drupal::configFactory()->get('se_quote.settings');
  if ($quote_status = $config->get('quote_status_term')) {
    \Drupal::service('se_core.set_field')
      ->setTaxonomyField($form, 'field_qu_status_ref', $quote_status);
  }
}
