<?php

/**
 * @file
 * StratosERP Webform integration module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\CloseDialogCommand;
use Drupal\Core\EventSubscriber\MainContentViewSubscriber;

/**
 * If this webform is ajax, modal or a dialog, add in a
 * callback to auto close it.
 *
 * Code from: https://www.drupal.org/project/webform/issues/3002966
 *
 * Implements hook_webform_submission_form_alter().
 */
function se_webform_integration_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  // Determine if current request is Ajax.
  // @see \Drupal\Core\Ajax\AjaxHelperTrait
  $is_ajax = FALSE;
  $wrapper_format = \Drupal::request()->get(MainContentViewSubscriber::WRAPPER_FORMAT);
  foreach (['drupal_ajax', 'drupal_modal', 'drupal_dialog'] as $wrapper) {
    if (strpos($wrapper_format, $wrapper) !== FALSE) {
      $is_ajax = TRUE;
      break;
    }
  }

  // Alter only the submit button's #ajax callback.
  if ($is_ajax && isset($form['actions']['submit']['#ajax'])) {
    $form['actions']['submit']['#ajax']['callback'] = '_se_webform_integration_webform_submission_form_submit_ajax';
  }
}

/**
 * Hook for the ajax callback.
 *
 * Code from: https://www.drupal.org/project/webform/issues/3002966
 *
 * @param array $form
 *   Nested array of form elements that comprise the webform.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 *
 * @return \Drupal\Core\Ajax\AjaxResponse
 */
function _se_webform_integration_webform_submission_form_submit_ajax(array &$form, FormStateInterface $form_state) {
  // If form is valid then close the dialog without displaying any confirmation.
  if (!$form_state->hasAnyErrors()) {
    $response = new AjaxResponse();
    $response->addCommand(new CloseDialogCommand());
    return $response;
  }

  /** @var \Drupal\webform\WebformSubmissionForm $form_object */
  $form_object = $form_state->getFormObject();

  /** @var \Drupal\Core\Ajax\AjaxResponse $response */
  $response = $form_object->submitAjaxForm($form, $form_state);

  return $response;
}
