<?php

/**
 * @file
 * Contains se_item.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_help().
 */
function se_item_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the se_item module.
    case 'help.page.se_item':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function se_item_theme() {
  $theme = [];
  $theme['se_item'] = [
    'render element' => 'elements',
    'file' => 'se_item.page.inc',
    'template' => 'se_item',
  ];
  $theme['se_item_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'se_item.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function se_item_theme_suggestions_se_item(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#se_item'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'se_item__' . $sanitized_view_mode;
  $suggestions[] = 'se_item__' . $entity->bundle();
  $suggestions[] = 'se_item__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'se_item__' . $entity->id();
  $suggestions[] = 'se_item__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function se_item_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'se_item') {
    if (isset($fields['field_it_code'])) {
      $fields['field_it_code']->addConstraint('UniqueItem', []);
    }
  }
}

