<?php

use Drupal\Core\Entity\EntityInterface;

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * @throws \Drupal\Core\TypedData\Exception\ReadOnlyException
 */
function se_item_entity_presave(EntityInterface $entity) {
  $total = 0;

  $bundles = [
    'se_bill'           => 'bi',
    'se_goods_receipt'  => 'gr',
    'se_invoice'        => 'in',
    'se_quote'          => 'qu',
    'se_purchase_order' => 'po',
  ];

  if ($entity->getEntityTypeId() != 'node' || !in_array($entity->bundle(), array_keys($bundles))) {
    return;
  }

  /** @var \Drupal\node\Entity\Node $entity */
  $items = $entity->{'field_' . $bundles[$entity->bundle()] . '_items'}->referencedEntities();

  foreach ($items as $ref_entity) {
    $total += $ref_entity->field_it_quantity->value * $ref_entity->field_it_price->value;
  }

  /** @var \Drupal\node\Entity\Node $entity */
  $entity->{'field_' . $bundles[$entity->bundle()] . '_total'}->setValue($total);
}

